const PDFDocument = require('pdfkit');
const { getLatestApprovedBy, getLatestFacultyApprover } = require('./reportService');
const env = require('../config/env');

function formatDate(value) {
  if (!value) {
    return 'Not set';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Not set';
  }

  return new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short'
  }).format(date);
}

function formatDateOnly(value) {
  if (!value) {
    return 'Not set';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Not set';
  }

  return new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium'
  }).format(date);
}

function text(value) {
  if (value === null || value === undefined || value === '') {
    return 'N/A';
  }

  return String(value);
}

function addHeader(doc, dataset, title) {
  doc.fillColor('#173449').fontSize(18).font('Helvetica-Bold').text('DwarPal', 50, 38);
  doc.fontSize(9).font('Helvetica').fillColor('#587086').text('Digital Gatepass Management System', 50, 60);
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#173449').text(title, 50, 92);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#587086')
    .text(`College: ${env.collegeName}`, 50, 112)
    .text(`Generated by: ${dataset.actor?.name || 'Admin'} (${dataset.actor?.role || 'admin'})`, 50, 127)
    .text(`Generated at: ${formatDate(dataset.generatedAt)}`, 50, 142);
  doc.moveTo(50, 164).lineTo(545, 164).strokeColor('#D8E2EA').lineWidth(1).stroke();
  doc.y = 180;
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    const pageNumber = index + 1;
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#7A8FA3')
      .text('Generated by DwarPal', 50, 760, { width: 220, align: 'left' })
      .text(`Page ${pageNumber} of ${range.count}`, 325, 760, { width: 220, align: 'right' });
  }
}

function ensureSpace(doc, height = 80) {
  if (doc.y + height > 735) {
    doc.addPage();
    doc.y = 50;
  }
}

function addSectionTitle(doc, title) {
  ensureSpace(doc, 40);
  doc.moveDown(0.4);
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#173449').text(title);
  doc.moveDown(0.4);
}

function addFilterSummary(doc, dataset) {
  addSectionTitle(doc, 'Applied Filters');
  const filters = dataset.publicFilters || {};
  const pairs = [
    ['Report Type', filters.reportType],
    ['Date Range', `${filters.from ? formatDateOnly(filters.from) : 'Start'} to ${filters.to ? formatDateOnly(filters.to) : 'Now'}`],
    ['Department', filters.department],
    ['Program', filters.program],
    ['Semester', filters.semester],
    ['Status', filters.status],
    ['Gatepass Type', filters.gatepassType],
    ['Leave Type', filters.leaveType]
  ];

  pairs.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#173449').text(`${label}: `, { continued: true });
    doc.font('Helvetica').fillColor('#587086').text(text(value));
  });
}

function addMetricCards(doc, summary) {
  addSectionTitle(doc, 'Executive Summary');
  const metrics = [
    ['Gatepasses', summary.totalGatepasses],
    ['Approved', summary.totalApproved],
    ['Rejected', summary.totalRejected],
    ['Pending', summary.totalPending],
    ['Out', summary.totalOut],
    ['Returned', summary.totalReturned],
    ['Late Returns', summary.totalLateReturns],
    ['Leave Requests', summary.totalLeaveRequests]
  ];
  const startX = 50;
  const cardWidth = 116;
  const cardHeight = 48;

  metrics.forEach((metric, index) => {
    const x = startX + (index % 4) * (cardWidth + 8);
    const y = doc.y + Math.floor(index / 4) * (cardHeight + 8);
    doc.roundedRect(x, y, cardWidth, cardHeight, 4).fillAndStroke('#F5F9FC', '#D8E2EA');
    doc.font('Helvetica').fontSize(8).fillColor('#587086').text(metric[0], x + 8, y + 8, { width: cardWidth - 16 });
    doc.font('Helvetica-Bold').fontSize(15).fillColor('#173449').text(String(metric[1] ?? 0), x + 8, y + 24, {
      width: cardWidth - 16
    });
  });

  doc.y += 112;
}

function addTable(doc, { title, columns, rows, maxRows = 60 }) {
  addSectionTitle(doc, title);

  if (!rows.length) {
    doc.font('Helvetica').fontSize(9).fillColor('#587086').text('No records found for the selected filters.');
    return;
  }

  const tableRows = rows.slice(0, maxRows);
  const widths = columns.map((column) => column.width || Math.floor(495 / columns.length));
  const rowHeight = 28;

  function drawHeader() {
    ensureSpace(doc, rowHeight + 8);
    let x = 50;
    const y = doc.y;
    doc.rect(50, y, 495, rowHeight).fill('#1F5A80');
    columns.forEach((column, index) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#FFFFFF').text(column.label, x + 4, y + 7, {
        width: widths[index] - 8,
        height: rowHeight - 8
      });
      x += widths[index];
    });
    doc.y = y + rowHeight;
  }

  drawHeader();

  tableRows.forEach((row, rowIndex) => {
    if (doc.y + rowHeight > 735) {
      doc.addPage();
      doc.y = 50;
      drawHeader();
    }

    let x = 50;
    const y = doc.y;
    doc.rect(50, y, 495, rowHeight).fill(rowIndex % 2 === 0 ? '#FFFFFF' : '#F7FAFC');
    columns.forEach((column, index) => {
      doc.font('Helvetica').fontSize(7.5).fillColor('#173449').text(text(row[column.key]), x + 4, y + 6, {
        width: widths[index] - 8,
        height: rowHeight - 6,
        ellipsis: true
      });
      x += widths[index];
    });
    doc.y = y + rowHeight;
  });

  if (rows.length > maxRows) {
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(8).fillColor('#587086').text(`Showing first ${maxRows} of ${rows.length} rows. Use Excel export for full details.`);
  }
}

function getReportTitle(dataset) {
  const labels = {
    all_gatepasses: 'All Gatepasses Report',
    student_report: 'Student Report',
    faculty_report: 'Faculty Report',
    department_wise_report: 'Department Report',
    monthly_report: 'Monthly Report',
    daily_report: 'Daily Report',
    custom_date_range: 'Custom Date Range Report',
    approval_report: 'Approval Report',
    pending_requests: 'Pending Requests Report',
    rejected_requests: 'Rejected Requests Report',
    out_returned_status: 'Out / Returned Status Report',
    leave_report: 'Leave Report',
    load_adjustment_report: 'Load Adjustment Report',
    coordinator_scope_report: 'Coordinator Scope Report',
    individual_student_history: 'Student Individual Report',
    individual_faculty_history: 'Faculty Individual Report'
  };

  return labels[dataset.filters.reportType] || 'DwarPal Admin Report';
}

function studentRows(dataset) {
  return dataset.studentSummaries.map((item) => ({
    name: item.name,
    id: item.enrollmentNo,
    department: item.department,
    semester: item.semester,
    total: item.totalGatepasses,
    approved: item.approvedCount,
    rejected: item.rejectedCount,
    pending: item.pendingCount
  }));
}

function gatepassRows(dataset) {
  return dataset.gatepasses.map((item) => ({
    id: item.gatepassId || item.passNumber,
    name: item.applicantSnapshot?.fullName || item.createdBy?.fullName,
    department: item.applicantSnapshot?.department || item.routingSnapshot?.department,
    date: formatDateOnly(item.outDate),
    status: item.status,
    approvedBy: getLatestApprovedBy(item)
  }));
}

function facultyRows(dataset) {
  return dataset.facultySummaries.map((item) => ({
    name: item.name,
    id: item.employeeId,
    department: item.department,
    coordinator: item.isCoordinator ? 'Yes' : 'No',
    leaves: item.leaveRequestsCount,
    load: item.loadAdjustmentCount,
    pending: item.pendingCount
  }));
}

function leaveRows(dataset) {
  return dataset.facultyLeaves.map((item) => ({
    id: item.requestNumber,
    name: item.facultyDetails?.name || item.createdBy?.fullName,
    type: item.leaveDetails?.leaveType,
    date: formatDateOnly(item.leaveDetails?.leaveFrom || item.shortLeave?.leaveDate),
    status: item.overallStatus,
    approvedBy: getLatestFacultyApprover(item)
  }));
}

function addInsights(doc, dataset) {
  addSectionTitle(doc, 'Insights');
  const insights = dataset.insights || {};
  const items = [
    insights.busiestDepartment
      ? `Highest request department: ${insights.busiestDepartment.department} (${insights.busiestDepartment.totalGatepasses} gatepasses)`
      : 'Highest request department: Not available',
    insights.peakRequestDay
      ? `Peak request day: ${insights.peakRequestDay.day} (${insights.peakRequestDay.count} requests)`
      : 'Peak request day: Not available',
    insights.mostActiveCoordinator
      ? `Most active coordinator: ${insights.mostActiveCoordinator.name}`
      : 'Most active coordinator: Not available',
    `Top frequent users included: ${Array.isArray(insights.topGatepassUsers) ? insights.topGatepassUsers.length : 0}`
  ];

  items.forEach((item) => {
    doc.font('Helvetica').fontSize(9).fillColor('#173449').text(`- ${item}`);
  });
}

function generatePdfBuffer(dataset) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true,
      info: {
        Title: getReportTitle(dataset),
        Author: 'DwarPal'
      }
    });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    addHeader(doc, dataset, getReportTitle(dataset));
    addFilterSummary(doc, dataset);
    addMetricCards(doc, dataset.dashboardSummary);
    addInsights(doc, dataset);

    addTable(doc, {
      title: 'Student Summary',
      columns: [
        { label: 'Student', key: 'name', width: 120 },
        { label: 'ID', key: 'id', width: 75 },
        { label: 'Dept', key: 'department', width: 70 },
        { label: 'Sem', key: 'semester', width: 38 },
        { label: 'Total', key: 'total', width: 45 },
        { label: 'Appr.', key: 'approved', width: 45 },
        { label: 'Rej.', key: 'rejected', width: 45 },
        { label: 'Pend.', key: 'pending', width: 57 }
      ],
      rows: studentRows(dataset),
      maxRows: 30
    });

    addTable(doc, {
      title: 'Gatepass Details',
      columns: [
        { label: 'ID', key: 'id', width: 75 },
        { label: 'Name', key: 'name', width: 115 },
        { label: 'Dept', key: 'department', width: 70 },
        { label: 'Date', key: 'date', width: 70 },
        { label: 'Status', key: 'status', width: 95 },
        { label: 'Approved By', key: 'approvedBy', width: 70 }
      ],
      rows: gatepassRows(dataset),
      maxRows: 50
    });

    addTable(doc, {
      title: 'Faculty / Leave / Load Adjustment',
      columns: [
        { label: 'Faculty', key: 'name', width: 125 },
        { label: 'ID', key: 'id', width: 70 },
        { label: 'Dept', key: 'department', width: 70 },
        { label: 'Coord.', key: 'coordinator', width: 48 },
        { label: 'Leaves', key: 'leaves', width: 50 },
        { label: 'Load', key: 'load', width: 45 },
        { label: 'Pending', key: 'pending', width: 87 }
      ],
      rows: facultyRows(dataset),
      maxRows: 35
    });

    addTable(doc, {
      title: 'Leave Requests',
      columns: [
        { label: 'Request', key: 'id', width: 75 },
        { label: 'Faculty', key: 'name', width: 120 },
        { label: 'Type', key: 'type', width: 50 },
        { label: 'Date', key: 'date', width: 75 },
        { label: 'Status', key: 'status', width: 85 },
        { label: 'Approved By', key: 'approvedBy', width: 90 }
      ],
      rows: leaveRows(dataset),
      maxRows: 45
    });

    addSectionTitle(doc, 'Notes / Remarks');
    doc.font('Helvetica').fontSize(9).fillColor('#587086').text(dataset.filters.notes || 'Signature / remarks placeholder');
    doc.moveDown(1);
    doc.font('Helvetica').fontSize(9).fillColor('#173449').text('Authorized Signature: ____________________________');

    addFooter(doc);
    doc.end();
  });
}

module.exports = {
  generatePdfBuffer
};
