const PDFDocument = require('pdfkit');
const { buildUserExportSections } = require('./reportService');
const env = require('../config/env');

function formatDate(value) {
  if (!value) {
    return 'Not set';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Not set';
  }

  return new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium',
    timeStyle: 'short'
  }).format(date);
}

function formatDateOnly(value) {
  if (!value) {
    return 'Not set';
  }

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return 'Not set';
  }

  return new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'medium'
  }).format(date);
}

function text(value) {
  if (value === null || value === undefined || value === '') {
    return 'N/A';
  }

  return String(value);
}

function getReportTitle(dataset) {
  const labels = {
    all_gatepasses: 'All Gatepasses Report',
    student_report: 'Student Report',
    faculty_report: 'Faculty Report',
    department_wise_report: 'Department Report',
    monthly_report: 'Monthly Report',
    daily_report: 'Daily Report',
    custom_date_range: 'Custom Date Range Report',
    approval_report: 'Approval Report',
    pending_requests: 'Pending Requests Report',
    rejected_requests: 'Rejected Requests Report',
    out_returned_status: 'Out / Returned Status Report',
    leave_report: 'Leave Report',
    load_adjustment_report: 'Load Adjustment Report',
    coordinator_scope_report: 'Coordinator Scope Report',
    individual_student_history: 'Student Individual Report',
    individual_faculty_history: 'Faculty Individual Report'
  };

  return labels[dataset.filters.reportType] || 'DwarPal Admin Report';
}

function addHeader(doc, dataset, title) {
  doc.fillColor('#173449').fontSize(18).font('Helvetica-Bold').text('DwarPal', 50, 38);
  doc.fontSize(9).font('Helvetica').fillColor('#587086').text('Digital Gatepass Management System', 50, 60);
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#173449').text(title, 50, 92);
  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#587086')
    .text(`College: ${env.collegeName}`, 50, 112)
    .text(`Generated by: ${dataset.actor?.name || 'Admin'} (${dataset.actor?.role || 'admin'})`, 50, 127)
    .text(`Generated at: ${formatDate(dataset.generatedAt)}`, 50, 142)
    .text(`Export scope: ${text(dataset.filters.exportScope)} | Partition: ${text(dataset.filters.recordPartition)}`, 50, 157);
  doc.moveTo(50, 179).lineTo(545, 179).strokeColor('#D8E2EA').lineWidth(1).stroke();
  doc.y = 192;
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    const pageNumber = index + 1;
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#7A8FA3')
      .text('Generated by DwarPal', 50, 760, { width: 220, align: 'left' })
      .text(`Page ${pageNumber} of ${range.count}`, 325, 760, { width: 220, align: 'right' });
  }
}

function ensureSpace(doc, height = 80) {
  if (doc.y + height > 730) {
    doc.addPage();
    doc.y = 50;
  }
}

function addSectionTitle(doc, title) {
  ensureSpace(doc, 32);
  doc.moveDown(0.4);
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#173449').text(title);
  doc.moveDown(0.35);
}

function addFilterSummary(doc, dataset) {
  addSectionTitle(doc, 'Applied Filters');
  const filters = dataset.publicFilters || {};
  const pairs = [
    ['Report Type', filters.reportType],
    ['Record Partition', filters.recordPartition],
    ['Detail Level', filters.detailLevel],
    ['Date Range', `${filters.from ? formatDateOnly(filters.from) : 'Start'} to ${filters.to ? formatDateOnly(filters.to) : 'Now'}`],
    ['Created Date Range', `${filters.createdFrom ? formatDateOnly(filters.createdFrom) : 'Start'} to ${filters.createdTo ? formatDateOnly(filters.createdTo) : 'Now'}`],
    ['Department', filters.department],
    ['Program', filters.program],
    ['Semester', filters.semester],
    ['Role Type', filters.roleType],
    ['Status', filters.status]
  ];

  pairs.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#173449').text(`${label}: `, { continued: true });
    doc.font('Helvetica').fillColor('#587086').text(text(value));
  });
}

function addMetricCards(doc, dataset) {
  addSectionTitle(doc, 'Export Summary');
  const metrics = [
    ['User Records', dataset.userRecordCount],
    ['Detailed Records', dataset.recordCount],
    ['Approved', dataset.dashboardSummary.totalApproved],
    ['Rejected', dataset.dashboardSummary.totalRejected],
    ['Pending', dataset.dashboardSummary.totalPending],
    ['Out', dataset.dashboardSummary.totalOut],
    ['Returned', dataset.dashboardSummary.totalReturned],
    ['Leave Requests', dataset.dashboardSummary.totalLeaveRequests]
  ];
  const startX = 50;
  const cardWidth = 116;
  const cardHeight = 48;

  metrics.forEach((metric, index) => {
    const x = startX + (index % 4) * (cardWidth + 8);
    const y = doc.y + Math.floor(index / 4) * (cardHeight + 8);
    doc.roundedRect(x, y, cardWidth, cardHeight, 4).fillAndStroke('#F5F9FC', '#D8E2EA');
    doc.font('Helvetica').fontSize(8).fillColor('#587086').text(metric[0], x + 8, y + 8, { width: cardWidth - 16 });
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#173449').text(String(metric[1] ?? 0), x + 8, y + 24, {
      width: cardWidth - 16
    });
  });

  doc.y += 112;
}

function addUserSummary(doc, section) {
  const fields = [
    ['User Type', section.userType],
    ['Role Type', section.roleType],
    ['Primary ID', section.primaryId],
    ['Department', section.department],
    ['Program', section.program],
    ['Semester', section.semester],
    ['Phone', section.phone],
    ['Email', section.email],
    ['Total Requests', section.totalRequests],
    ['Approved', section.approvedCount],
    ['Rejected', section.rejectedCount],
    ['Pending', section.pendingCount],
    ['Out', section.outCount],
    ['Returned', section.returnedCount]
  ];

  fields.forEach(([label, value], index) => {
    if (index % 2 === 0) {
      ensureSpace(doc, 16);
    }

    doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#173449').text(`${label}: `, { continued: true });
    doc.font('Helvetica').fillColor('#587086').text(text(value));
  });
}

function addDetailBlocks(doc, details) {
  if (!details.length) {
    doc.font('Helvetica').fontSize(9).fillColor('#587086').text('No detailed records found for this user.');
    return;
  }

  details.forEach((detail, index) => {
    ensureSpace(doc, 110);
    doc.roundedRect(50, doc.y, 495, 88, 6).fillAndStroke(index % 2 === 0 ? '#FFFFFF' : '#F7FAFC', '#D8E2EA');
    const startY = doc.y + 8;
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#173449').text(`${detail.requestType} | ${detail.gatepassId}`, 60, startY);
    doc
      .font('Helvetica')
      .fontSize(8.5)
      .fillColor('#587086')
      .text(
        `Date: ${formatDate(detail.gatepassDate)} | Out: ${text(detail.outTime)} | Return: ${text(detail.returnTime)} | Actual Return: ${formatDate(detail.actualReturnTime)}`,
        60,
        startY + 16,
        { width: 470 }
      )
      .text(`Status: ${text(detail.approvalStatus)} | Actioned By: ${text(detail.actionBy)} | Stage: ${text(detail.currentWorkflowStage)}`, 60, startY + 32, {
        width: 470
      })
      .text(`Reason: ${text(detail.reason)}`, 60, startY + 48, { width: 470 })
      .text(`Destination: ${text(detail.destination)} | Vehicle: ${text(detail.vehicleNumber)} | Rejection: ${text(detail.rejectionReason)}`, 60, startY + 64, {
        width: 470
      });
    doc.y += 98;
  });
}

function addUserSections(doc, dataset) {
  const sections = buildUserExportSections(dataset);

  sections.forEach((section, index) => {
    if (index > 0) {
      doc.addPage();
      doc.y = 50;
    }

    addSectionTitle(doc, `${section.name}`);
    addUserSummary(doc, section);

    doc.moveDown(0.8);
    addSectionTitle(doc, 'Detailed Records');
    addDetailBlocks(doc, section.details);
  });
}

function generatePdfBuffer(dataset) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true,
      info: {
        Title: getReportTitle(dataset),
        Author: 'DwarPal'
      }
    });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    addHeader(doc, dataset, getReportTitle(dataset));
    addFilterSummary(doc, dataset);
    addMetricCards(doc, dataset);

    if (dataset.filters.detailLevel !== 'summary_only') {
      addSectionTitle(doc, 'User Record Sections');
      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#587086')
        .text('Each user section includes overview details and all matching gatepass or leave records with page breaks for multi-user exports.');
      addUserSections(doc, dataset);
    }

    addFooter(doc);
    doc.end();
  });
}

module.exports = {
  generatePdfBuffer
};
